columns:
  - CustomerID: int
  - ProdTaken: int  
  - Age: float
  - CityTier: int
  - DurationOfPitch: float
  - NumberOfPersonVisiting: int
  - NumberOfFollowups: float
  - PreferredPropertyStar: float
  - NumberOfTrips: float
  - Passport: int
  - PitchSatisfactionScore: int
  - OwnCar: int
  - NumberOfChildrenVisiting: float
  - MonthlyIncome: float
  - TypeofContact: category
  - Occupation: category
  - Gender: category
  - ProductPitched: category
  - MaritalStatus: category
  - Designation: category

numerical_columns:
  - CustomerID
  - ProdTaken
  - Age
  - CityTier
  - DurationOfPitch
  - NumberOfPersonVisiting
  - NumberOfFollowups
  - PreferredPropertyStar
  - NumberOfTrips
  - Passport
  - PitchSatisfactionScore
  - OwnCar
  - NumberOfChildrenVisiting
  - MonthlyIncome

categorical_columns:
  - TypeofContact
  - Occupation
  - Gender
  - ProductPitched
  - MaritalStatus
  - Designation

drop_columns:
  - CustomerID

# for transformation

discrete_columns:
  - CityTier
  - NumberOfPersonVisiting
  - NumberOfFollowups
  - PreferredPropertyStar
  - NumberOfTrips
  - Passport
  - PitchSatisfactionScore
  - OwnCar
  - NumberOfChildrenVisiting

continuous_columns:
  - Age
  - DurationOfPitch
  - MonthlyIncome

transform_columns:
  - DurationOfPitch
  - MonthlyIncome